import clases as cl

N_GAMES = 2
N_SIMULATIONS = 3492
PLAYERS_RANGE = 6
INITIAL_BUDGET = 100000
BIG_BLIND = 5000
N_REPS = 100

pg = cl.PlayGround(N_REPS, N_GAMES, N_SIMULATIONS, PLAYERS_RANGE, INITIAL_BUDGET, BIG_BLIND)
pg.train()